version: '3.8'
      
services:
  db:
    image: mariadb-image:nextcloud
    container_name: ${DB_CONTAINER_NAME}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    container_name: ${APP_CONTAINER_NAME}
    image: nextcloud:fpm
    depends_on:
      - db
    volumes:
      - ./nextcloud:/var/www/html
    restart: unless-stopped

  web:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:latest
    ports:
      - 8001:80
    depends_on:
      - nextcloud
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/nginx.conf.d:/etc/nginx/conf.d
      - ./nextcloud:/var/www/html
    restart: unless-stopped

